---
# handlers file for mesos-slave
- name: restart mesos-slave
  service: name=mesos-slave state=restarted

- name: reload mesos-slave service
  sudo: yes
  shell: systemctl daemon-reload
  notify: restart mesos-slave